In [5]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

url = f"http://www.skyloungeamsterdam.com/nl/"
r = requests.get(url)
page = r.text

menu = BeautifulSoup(page, 'html.parser')

if r.status_code == 200:
    menu_items = menu.select(".foodpost") # .get_text() only takes the text, without h1 / h2 / etc

In [6]:
menu2 = []
# for menu_item in menu_items:
   
    
for menu_item in menu_items:
    title = menu_item.select(".foodtitle")
    price = menu_item.select(".foodprice")
    
    menu2.append([title[0].get_text().strip(), price[0].get_text().replace("€", "").replace(",", ".").strip()])
    
print(menu2)

    
# print(menu[0].get_text())
# for title in titles:
#     print(title.get_text().strip())
# for price in prices:
#     print(price.get_text().strip())

[['Croque Monsieur', '14.00'], ['Tom Kha kai', '14.00'], ['Pork belly', '14.50'], ['Caesar salad', '16.00'], ['Gambas', '18.00'], ['Pumpkin risotto', '14.00'], ['Crispy Peking duck', '14.00'], ['Sliders, mini burgers 3 pcs', '17.50'], ['Blue corn tortilla 3 pcs', '16.50'], ['Hotdogs 3 pcs', '19.00'], ['Flammkuchen pulled chicken', '14.00'], ['Flammkuchen vegetables', '12.00'], ['Veal ”Bitterballen” from ”Kellenaers” 6 pcs', '9.50'], ['Crunchy chicken 6 pcs', '9.50'], ['Fried mix platter 16 pcs', '27.50'], ['Fried Dutch “Kibbeling” 6 pcs', '9.50'], ['Nachos', '12.50'], ['Grilled chicken sausage', '12.00'], ['French fries from the ”FRIETBOUTIQUE”', '7.50'], ['Cheese platter from Fromagerie L’amuse “Betty’s Choice”', '16.00'], ['Fine de Claire No.2 oysters from “David Hervé” 6 pcs', '20.00'], ['Fine de Claire No.2 oysters from “David Hervé” 12 pcs', '35.00'], ['Tuna roll 8 pcs', '19.00'], ['Spicy crab roll 8 pcs', '19.00'], ['Smoked eel 8 pcs', '19.00'], ['Sushi mix platter 24 pcs', '47.00'], ['Crunchy tuna crackers 4 pcs', '13.00'], ['Poke bowl salmon 1 bowl', '15.00'], ['Poke bowl tuna 1 bowl', '16.00'], ['‘Stroopwafel’ éclair', '6.00'], ['Apple pie', '5.50'], ['Fudge cake', '6.00'], ['Banana, coconut and praline', '8.50'], ['Lemon, mango and strawberry (lactose free)', '8.50'], ['White chocolate, pistachio and oreo cookies', '8.50'], ['Mixed nuts', '7.50'], ['Marinated olives', '7.50'], ['Chicken Yakatori 8 pcs', '12.50'], ['Nachos', '12.50'], ['Pizza Margherita', '17.50'], ['Pizza 4 cheeses', '17.50'], ['Pizza Pepperoni', '17.50']]

In [3]:
items = []
for i, item in enumerate(menu2):
    item = {
        "title" : menu2[i][0],
        "price" : float(menu2[i][1])
    }
    items.append(item)
print(items)

[{'title': 'Croque Monsieur', 'price': 14.0}, {'title': 'Tom Kha kai', 'price': 14.0}, {'title': 'Pork belly', 'price': 14.5}, {'title': 'Caesar salad', 'price': 16.0}, {'title': 'Gambas', 'price': 18.0}, {'title': 'Pumpkin risotto', 'price': 14.0}, {'title': 'Crispy Peking duck', 'price': 14.0}, {'title': 'Sliders, mini burgers 3 pcs', 'price': 17.5}, {'title': 'Blue corn tortilla 3 pcs', 'price': 16.5}, {'title': 'Hotdogs 3 pcs', 'price': 19.0}, {'title': 'Flammkuchen pulled chicken', 'price': 14.0}, {'title': 'Flammkuchen vegetables', 'price': 12.0}, {'title': 'Veal ”Bitterballen” from ”Kellenaers” 6 pcs', 'price': 9.5}, {'title': 'Crunchy chicken 6 pcs', 'price': 9.5}, {'title': 'Fried mix platter 16 pcs', 'price': 27.5}, {'title': 'Fried Dutch “Kibbeling” 6 pcs', 'price': 9.5}, {'title': 'Nachos', 'price': 12.5}, {'title': 'Grilled chicken sausage', 'price': 12.0}, {'title': 'French fries from the ”FRIETBOUTIQUE”', 'price': 7.5}, {'title': 'Cheese platter from Fromagerie L’amuse “Betty’s Choice”', 'price': 16.0}, {'title': 'Fine de Claire No.2 oysters from “David Hervé” 6 pcs', 'price': 20.0}, {'title': 'Fine de Claire No.2 oysters from “David Hervé” 12 pcs', 'price': 35.0}, {'title': 'Tuna roll 8 pcs', 'price': 19.0}, {'title': 'Spicy crab roll 8 pcs', 'price': 19.0}, {'title': 'Smoked eel 8 pcs', 'price': 19.0}, {'title': 'Sushi mix platter 24 pcs', 'price': 47.0}, {'title': 'Crunchy tuna crackers 4 pcs', 'price': 13.0}, {'title': 'Poke bowl salmon 1 bowl', 'price': 15.0}, {'title': 'Poke bowl tuna 1 bowl', 'price': 16.0}, {'title': '‘Stroopwafel’ éclair', 'price': 6.0}, {'title': 'Apple pie', 'price': 5.5}, {'title': 'Fudge cake', 'price': 6.0}, {'title': 'Banana, coconut and praline', 'price': 8.5}, {'title': 'Lemon, mango and strawberry (lactose free)', 'price': 8.5}, {'title': 'White chocolate, pistachio and oreo cookies', 'price': 8.5}, {'title': 'Mixed nuts', 'price': 7.5}, {'title': 'Marinated olives', 'price': 7.5}, {'title': 'Chicken Yakatori 8 pcs', 'price': 12.5}, {'title': 'Nachos', 'price': 12.5}, {'title': 'Pizza Margherita', 'price': 17.5}, {'title': 'Pizza 4 cheeses', 'price': 17.5}, {'title': 'Pizza Pepperoni', 'price': 17.5}]

In [4]:
df = pd.DataFrame(items)
df

    price                                              title
0    14.0                                    Croque Monsieur
1    14.0                                        Tom Kha kai
2    14.5                                         Pork belly
3    16.0                                       Caesar salad
4    18.0                                             Gambas
5    14.0                                    Pumpkin risotto
6    14.0                                 Crispy Peking duck
7    17.5                        Sliders, mini burgers 3 pcs
8    16.5                           Blue corn tortilla 3 pcs
9    19.0                                      Hotdogs 3 pcs
10   14.0                         Flammkuchen pulled chicken
11   12.0                             Flammkuchen vegetables
12    9.5        Veal ”Bitterballen” from ”Kellenaers” 6 pcs
13    9.5                              Crunchy chicken 6 pcs
14   27.5                           Fried mix platter 16 pcs
15    9.5                      Fried Dutch “Kibbeling” 6 pcs
16   12.5                                             Nachos
17   12.0                            Grilled chicken sausage
18    7.5              French fries from the ”FRIETBOUTIQUE”
19   16.0  Cheese platter from Fromagerie L’amuse “Betty’...
20   20.0  Fine de Claire No.2 oysters from “David Hervé”...
21   35.0  Fine de Claire No.2 oysters from “David Hervé”...
22   19.0                                    Tuna roll 8 pcs
23   19.0                              Spicy crab roll 8 pcs
24   19.0                                   Smoked eel 8 pcs
25   47.0                           Sushi mix platter 24 pcs
26   13.0                        Crunchy tuna crackers 4 pcs
27   15.0                            Poke bowl salmon 1 bowl
28   16.0                              Poke bowl tuna 1 bowl
29    6.0                               ‘Stroopwafel’ éclair
30    5.5                                          Apple pie
31    6.0                                         Fudge cake
32    8.5                        Banana, coconut and praline
33    8.5         Lemon, mango and strawberry (lactose free)
34    8.5        White chocolate, pistachio and oreo cookies
35    7.5                                         Mixed nuts
36    7.5                                   Marinated olives
37   12.5                             Chicken Yakatori 8 pcs
38   12.5                                             Nachos
39   17.5                                   Pizza Margherita
40   17.5                                    Pizza 4 cheeses
41   17.5                                    Pizza Pepperoni

In [9]:
df["price"].describe()

count    42.000000
mean     14.904762
std       7.639147
min       5.500000
25%       9.500000
50%      14.000000
75%      17.500000
max      47.000000
Name: price, dtype: float64

In [10]:
df["price"].sum()

626.0

In [13]:
df["price"].count()

42